# Generated by Django 3.2.9 on 2021-11-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_credential_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='password',
        ),
        migrations.AddField(
            model_name='credential',
            name='ip',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
